# Generated by Django 5.2 on 2025-05-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KingsBurgers', '0003_inventario'),
        ('KingsBurgers', '0004_pedido_pago'),
    ]

    operations = [
    ]
