# Generated by Django 5.2 on 2025-05-05 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsBurgers', '0004_pedido_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(blank=True, default=None, null=True)),
                ('desde', models.DateTimeField(blank=True, null=True)),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KingsBurgers.producto')),
            ],
        ),
    ]
