# Generated by Django 5.2 on 2025-05-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsBurgers', '0005_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='adicionales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adiciones', to='KingsBurgers.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
