# Generated by Django 5.2 on 2025-05-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsBurgers', '0005_merge_0003_inventario_0004_pedido_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='adicionales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adiciones', to='KingsBurgers.cartitem'),
        ),
    ]
