# Generated by Django 5.2 on 2025-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsBurgers', '0006_cartitem_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
